## 1. Put the database in the data subfolder in the src directory.

Done

## 2. Create a connection to the database using the sqlite3 library.

In [24]:
import sqlite3
import pandas as pd
conn = sqlite3.connect('../data/checking-logs.sqlite')

## 3. Get the schema of the pageviews table using pd.io.sql.read_sql() and the query "PRAGMA table_info(pageviews);".

In [25]:

query = "PRAGMA table_info(pageviews);"
pageviews = pd.io.sql.read_sql(query, conn)
pageviews

   cid      name       type  notnull dflt_value  pk
0    0     index    INTEGER        0       None   0
1    1       uid       TEXT        0       None   0
2    2  datetime  TIMESTAMP        0       None   0

## 4. Get only the first ten rows of the pageviews table to see what the table looks like.

In [26]:
query = 'SELECT * FROM pageviews LIMIT 10;'
first_ten_pagewiews = pd.io.sql.read_sql(query, conn).set_index('index')
first_ten_pagewiews

           uid                    datetime
index
0      admin_1  2020-04-17 12:01:08.463179
1      admin_1  2020-04-17 12:01:23.743946
2      admin_3  2020-04-17 12:17:39.287778
3      admin_3  2020-04-17 12:17:40.001768
4      admin_1  2020-04-17 12:27:30.646665
5      admin_1  2020-04-17 12:35:44.884757
6      admin_1  2020-04-17 12:35:52.735016
7      admin_3  2020-04-17 12:36:21.401412
8      admin_3  2020-04-17 12:36:22.023355
9      admin_1  2020-04-17 13:55:19.129243

## 5. Use one query to get the subtable where:
Only "uid" and "datetime" are used.
Only user data (user_*), not admin data, is used.
It is sorted by "uid" in ascending order.
The index column is "datetime".
"datetime" is converted to a DatetimeIndex.
The name of the dataframe is pageviews.

In [27]:
query = ('SELECT uid, datetime FROM pageviews WHERE uid LIKE "user_%" ORDER BY uid ASC;')
pageviews = pd.io.sql.read_sql(query, conn, index_col='datetime', parse_dates=['datetime'])
pageviews

                                uid
datetime
2020-04-26 21:53:59.624136   user_1
2020-04-26 22:06:19.478143   user_1
2020-04-26 22:12:09.614497   user_1
2020-04-30 19:29:01.831635   user_1
2020-05-05 20:26:32.894852   user_1
...                             ...
2020-04-29 16:51:21.877630  user_30
2020-05-09 20:30:47.034282  user_30
2020-05-22 11:30:18.368990   user_5
2020-05-21 16:28:28.217529   user_9
2020-05-21 16:36:40.915488   user_9

[987 rows x 1 columns]

## 6. Close the connection to the database.

In [28]:
conn.close()