#### 1. Read:

In [1]:
import pandas as pd
df = pd.read_csv('../data/feed-views.log',
                 sep='\t',
                 names=['datatime', 'user'], 
                 skiprows=[2,3],skipfooter=2,
                 engine='python',
                 index_col='datatime')

#### 2. Rename:

In [2]:
df.index.name = 'data_time'

#### 3. To csv:

In [3]:
df.to_csv('../data/feed-views-semicolon.log', sep=';')

#### 4. Read csv:

In [4]:
df.head()

                              user
data_time
2020-04-17 12:01:08.463179   artem
2020-04-17 12:01:23.743946   artem
2020-04-17 12:35:52.735016   artem
2020-04-17 12:36:21.401412  oksana
2020-04-17 12:36:22.023355  oksana

In [5]:
df.tail()

                                 user
data_time
2020-05-21 16:36:40.915488  ekaterina
2020-05-21 17:49:36.429237      maxim
2020-05-21 18:45:20.441142  valentina
2020-05-21 23:03:06.457819      maxim
2020-05-21 23:23:49.995349      pavel