## 1. Create a connection to the database using the sqlite3 library.

In [9]:
import sqlite3
import pandas as pd
conn = sqlite3.connect('../data/checking-logs.sqlite')

## 2. Get the schema of the test table.

In [10]:
query = "PRAGMA TABLE_INFO(test);"
test_schema = pd.read_sql_query(query, conn)
print(test_schema)

   cid             name       type  notnull dflt_value  pk
0    0              uid       TEXT        0       None   0
1    1          labname       TEXT        0       None   0
2    2  first_commit_ts  TIMESTAMP        0       None   0
3    3    first_view_ts  TIMESTAMP        0       None   0

## 3. Get only the first ten rows of the test table to see what it looks like.

In [11]:
test = pd.read_sql_query("SELECT * FROM test", conn)
test

        uid   labname             first_commit_ts               first_view_ts
0    user_1    laba04  2020-04-26 17:06:18.462708  2020-04-26 21:53:59.624136
1    user_1   laba04s  2020-04-26 17:12:11.843671  2020-04-26 21:53:59.624136
2    user_1    laba05  2020-05-02 19:15:18.540185  2020-04-26 21:53:59.624136
3    user_1    laba06  2020-05-17 16:26:35.268534  2020-04-26 21:53:59.624136
4    user_1   laba06s  2020-05-20 12:23:37.289724  2020-04-26 21:53:59.624136
5    user_1  project1  2020-05-14 20:56:08.898880  2020-04-26 21:53:59.624136
6   user_10    laba04  2020-04-25 08:24:52.696624  2020-04-18 12:19:50.182714
7   user_10   laba04s  2020-04-25 08:37:54.604222  2020-04-18 12:19:50.182714
8   user_10    laba05  2020-05-01 19:27:26.063245  2020-04-18 12:19:50.182714
9   user_10    laba06  2020-05-19 11:39:28.885637  2020-04-18 12:19:50.182714
10  user_10   laba06s  2020-05-20 07:37:31.175817  2020-04-18 12:19:50.182714
11  user_10  project1  2020-05-12 20:12:28.056618  2020-04-18 12:19:50.182714
12  user_14    laba04  2020-04-18 15:14:00.312338  2020-04-18 10:53:52.623447
13  user_14   laba04s  2020-04-18 22:30:30.247628  2020-04-18 10:53:52.623447
14  user_14    laba05  2020-04-30 11:33:04.523118  2020-04-18 10:53:52.623447
15  user_14  project1  2020-05-05 21:35:43.554986  2020-04-18 10:53:52.623447
16  user_17    laba04  2020-04-23 14:24:29.947554  2020-04-18 10:56:55.833899
17  user_17   laba04s  2020-04-25 12:10:56.414175  2020-04-18 10:56:55.833899
18  user_17    laba05  2020-05-02 13:21:24.045876  2020-04-18 10:56:55.833899
19  user_17    laba06  2020-05-21 15:21:31.567615  2020-04-18 10:56:55.833899
20  user_17   laba06s  2020-05-21 17:39:17.783615  2020-04-18 10:56:55.833899
21  user_17  project1  2020-04-18 07:56:45.408648  2020-04-18 10:56:55.833899
22  user_18    laba04  2020-04-26 19:48:11.822365  2020-04-26 22:49:29.243278
23  user_18   laba04s  2020-04-26 20:03:56.935458  2020-04-26 22:49:29.243278
24  user_18    laba05  2020-05-03 13:01:34.848756  2020-04-26 22:49:29.243278
25  user_18  project1  2020-05-11 10:10:04.166881  2020-04-26 22:49:29.243278
26  user_19    laba04  2020-04-20 19:05:01.297780  2020-04-21 20:30:38.034966
27  user_19    laba05  2020-05-02 15:16:13.586405  2020-04-21 20:30:38.034966
28  user_19    laba06  2020-05-19 10:25:54.121465  2020-04-21 20:30:38.034966
29  user_19   laba06s  2020-05-21 13:27:06.705881  2020-04-21 20:30:38.034966
30  user_19  project1  2020-05-14 10:33:45.495389  2020-04-21 20:30:38.034966
31  user_21    laba04  2020-04-21 17:48:00.487806  2020-04-22 22:40:36.824081
32  user_21   laba04s  2020-04-22 20:09:21.857747  2020-04-22 22:40:36.824081
33  user_21    laba05  2020-05-02 14:05:40.013959  2020-04-22 22:40:36.824081
34  user_21    laba06  2020-05-19 19:30:14.644328  2020-04-22 22:40:36.824081
35  user_21  project1  2020-05-10 15:21:05.442755  2020-04-22 22:40:36.824081
36  user_25    laba04  2020-04-20 19:16:50.673054  2020-05-09 23:54:54.260791
37  user_25   laba04s  2020-04-26 21:07:56.952117  2020-05-09 23:54:54.260791
38  user_25    laba05  2020-05-01 13:02:27.357650  2020-05-09 23:54:54.260791
39  user_25    laba06  2020-05-18 17:07:47.988807  2020-05-09 23:54:54.260791
40  user_25   laba06s  2020-05-20 14:02:26.512032  2020-05-09 23:54:54.260791
41  user_25  project1  2020-05-08 11:10:28.100852  2020-05-09 23:54:54.260791
42  user_28    laba04  2020-04-22 21:47:19.707242  2020-05-10 21:07:50.350946
43  user_28   laba04s  2020-04-26 15:53:44.906136  2020-05-10 21:07:50.350946
44  user_28    laba05  2020-05-01 18:29:11.968537  2020-05-10 21:07:50.350946
45  user_28    laba06  2020-05-17 17:08:48.257050  2020-05-10 21:07:50.350946
46  user_28   laba06s  2020-05-20 20:42:44.423160  2020-05-10 21:07:50.350946
47  user_28  project1  2020-05-12 14:42:19.166414  2020-05-10 21:07:50.350946
48   user_3    laba04  2020-04-23 20:29:14.054364  2020-05-08 10:53:47.123832
49   user_3   laba04s  2020-04-23 20:40:26.883591  2020-05-08 10:53:47.123832
50   user_3    laba05  2020-05-01 11:29:17.988118  2020-05-08 10:53:47.123832
51   user_3    laba06  2020-05-17 09:56:40.480319  2020-05-08 10:53:47.123832
52   user_3   laba06s  2020-05-19 08:42:50.851878  2020-05-08 10:53:47.123832
53   user_3  project1  2020-05-07 21:02:52.885133  2020-05-08 10:53:47.123832
54  user_30    laba04  2020-04-18 13:36:53.971502  2020-04-17 22:46:26.785035
55  user_30   laba04s  2020-04-18 14:51:37.498399  2020-04-17 22:46:26.785035
56  user_30    laba05  2020-05-01 19:31:18.375833  2020-04-17 22:46:26.785035
57  user_30    laba06  2020-05-19 17:53:15.088248  2020-04-17 22:46:26.785035
58  user_30  project1  2020-04-22 12:36:24.053518  2020-04-17 22:46:26.785035

## 4. Find the minimum value of the delta between the first commit and the deadline of the corresponding lab for all users using only one query.
Do this by joining the table with the deadlines table.
The difference should be displayed in hours.
Do not take lab project1 into account; it has longer deadlines and will be an outlier.
The value should be stored in the dataframe df_min with the corresponding uid.

In [12]:
query = "SELECT uid, MIN((deadlines - strftime('%s',first_commit_ts))/3600.0) as min_time FROM test t LEFT JOIN deadlines d ON t.labname = d.labs WHERE t.labname NOT LIKE 'project1';"
df_min = pd.read_sql_query(query, conn)
df_min

       uid  min_time
0  user_25    2.8675

## 5. Do the same thing for the maximum, but use only one query. The dataframe name is df_max.

In [13]:
query = "SELECT uid, MAX((deadlines - strftime('%s',first_commit_ts))/3600.0) as max_time FROM test t LEFT JOIN deadlines d ON t.labname = d.labs WHERE t.labname NOT LIKE 'project1' "
df_max = pd.read_sql_query(query, conn)
df_max

       uid  max_time
0  user_30   202.385

## 6. Do the same thing, but for the average. Use only one query. This time, your dataframe should not include the uid column. The dataframe name is df_avg.

In [14]:
query = "SELECT uid, AVG((deadlines - strftime('%s',first_commit_ts))/3600.0) as avg_time FROM test t LEFT JOIN deadlines d ON t.labname = d.labs WHERE t.labname NOT LIKE 'project1'"
df_avg = pd.read_sql_query(query, conn)
df_avg

      uid   avg_time
0  user_1  89.687841

## 7. We want to test the hypothesis that users who visited the newsfeed just a few times have a lower delta between the first commit and the deadline. To do this, calculate the correlation coefficient between the number of pageviews and the difference.
Using only one query, create a table with the following columns: "uid", "avg_diff", and "pageviews".
"uid" is the uids that exist in the test.
"avg_diff" is the average delta between the first commit and the lab deadline per user.
"pageviews" is the number of Newsfeed visits per user.
Do not take the lab project1 into account.
Store it in the dataframe views_diff.
Use the Pandas corr() method to calculate the correlation coefficient between the number of pageviews and the difference.

In [15]:
query = """
        SELECT 
        t.uid, 
        (AVG((deadlines - strftime('%s',first_commit_ts))/3600.0)) AS avg_diff, 
        pv.pageviews
        FROM test AS t 
        LEFT JOIN deadlines AS d
            ON t.labname = d.labs 
        LEFT JOIN (
            SELECT 
            uid,
            COUNT(*) AS pageviews
            FROM pageviews
            GROUP BY uid
        ) AS pv ON pv.uid = t.uid
        WHERE t.labname NOT LIKE 'project1' 
        GROUP BY t.uid;
        """

views_diff = pd.read_sql_query(query, conn)
corr = views_diff['pageviews'].corr(views_diff['avg_diff'])
print(corr)
views_diff

0.27914346425426556

        uid    avg_diff  pageviews
0    user_1   65.119778         28
1   user_10   75.242444         89
2   user_14  159.568796        143
3   user_17   62.207667         47
4   user_18    6.368148          3
5   user_19   99.440417         16
6   user_21   96.111181         10
7   user_25   93.474944        179
8   user_28   86.793833        149
9    user_3  105.738222        317
10  user_30  145.528681          3

## 8. Close the connection.

In [16]:
conn.close()